### ISSUE TITLE
The plugin doesn't redirect to the download page or open files

### ISSUE THREAD

**Issue by Pireo** [v1k45/1337x-qBittorrent-search-plugin#1]
If I click on a file, nothing happens. Ah, it also seems to be limited to 40 results.
BTW, thanks a lot for this great plugin! I proposed it as official.

**Comment by v1k45** [comment]
Hi @Pireo this issue has been fixed now. You can update your local plugin to get the download links working.

Also, there is no limit on number of results. The plugin returns all links available on 1337x for a search term by paginating through every page.

Thanks for reporting :)

**Comment by Pireo** [comment]
Thank you for the fix ;), however still limited to 40 results (that's the maximum number it shows to me), anyway, this is tolerable.

UPDATE: it seems depending on what I search, I get different number of results, for exemple with "ubuntu" I get 143, with "movie" just 32.

**Comment by ghost** [comment]
Hello. I'm having the above problem. With "nem comics" as the search term I get 218 results on 1337x and 40 via your plugin.
