### ISSUE TITLE
click on a search result item from 1337x --> nothing happens.

### ISSUE THREAD

**Issue by WaterSibilantFalling** [v1k45/1337x-qBittorrent-search-plugin#2]
I don't know if this is related to issue #1  but in the qBittorrent search, any results returned for https://1337x.to  don't work. I click on the link and absolutely nothing happens: the "add torrent" dialog does not appear, and the torrent is not added to the download list. 

1337x plugin version 1.1
Linux 4.10.0-rc6-686-pae \#1 SMP Debian 4.10\~rc6-1\~exp2 (2017-02-02) i686 GNU/Linux
qBittorrent  3.4.0alpha, libtorrent 1.1.4.0

**Comment by v1k45** [comment]
Torrents can be downloaded by selecting result and clicking on "Download" button in the bottom of the window.

If your torrents are still not being downloaded, a possible reason for this can be your IP Address being blacklisted by CloudFlare's Anti-DDOS which is used by itorrents.

To test this, you can click "Go to description page" button and select "ITORRENTS MIRROR" in the torrents section in the page. If you see a Cloudflare captcha/interstitial, it means your IP is blacklisted.

Unfortunately, there is no known way to circumvent this behaviour, you'll have to solve the captcha first to download.

**Comment by H48** [comment]
I have the same issue. Clicking on the "Download" button in the bottom of the window does not do anything.
When I go to the description page, I see neither any "ITORRENTS MIRROR" nor any "torrents section".
Any help appreciated.

**Comment by v1k45** [comment]
@H48 

You can see it after clicking on download "TORRENT DOWNLOAD" button.
![screenshot from 2017-08-16 01-07-19](https://user-images.githubusercontent.com/7877501/29332912-533b060e-821f-11e7-966f-21454c7a81e8.png)

**Comment by H48** [comment]
Thank you.  The itorrents mirror works without any captcha and starts downloading the .torrent file.

**Comment by v1k45** [comment]
Ah, just noticed that 1337x has updated it's css class name for the download button. Most probably that is breaking the plugin.

I'll push a fix in a day or two. Thanks for reporting :)

**Comment by H48** [comment]
thanks for fixing! :-)

**Comment by WaterSibilantFalling** [comment]
thanks from me too.

**Comment by v1k45** [comment]
@AbsurdMagpieScrutinies @H48, I've fixed this issue. You can now update your installed search plugin using the same menu you installed it.

Thanks.
