### ISSUE TITLE
Search returns no result

### ISSUE THREAD

**Issue by mrinmaydhar** [v1k45/1337x-qBittorrent-search-plugin#4]
![2018-04-14](https://user-images.githubusercontent.com/11980028/38766706-557eb95a-3ff3-11e8-9958-b8fdd1b1f526.png)
Searching for anything returns no result. I have done a total windows reset. Python was automatically installed by qBittorrent. Search results are returned by Rarbg, Rutracker, btdb etc.

**Comment by v1k45** [comment]
Hmm, works fine for me.
![screenshot v3.3.7](https://i.imgur.com/ApMDZXc.png)

**Comment by v1k45** [comment]
I'll check if it has something to do with the version.

**Comment by v1k45** [comment]
Are you able to access https://1337.to normally from your browser?

If you see a cloudflare captcha/ loading interstitial before seeing the actual site, nothing can be done about this.

**Comment by mrinmaydhar** [comment]
Apparently I cannot access 1337 from my browser. I'll try using proxy settings. I'll close the issue now.

**Comment by v1k45** [comment]
@mrinmaydhar If the other 1337x domains like 1337x.st x1337x.ws x1337x.eu work for you, you can update the script and change the `LEETX_DOMAIN` variable.
